language: python

python:
  - "3.7"

install:
  - pip install Sphinx sphinx_rtd_theme codecov packaging
  - "python -c $'import os, packaging.version as version\\nv = version.parse(os.environ.get(\"TRAVIS_TAG\", \"1.0\")).public\\nwith open(\"VERSION\", \"w\") as f: f.write(v)'"
  - python setup.py install
  - cd docs
  - make clean html
  - cd ..

script:
  - python setup.py nosetests --with-coverage --cover-package=networkfox
